version: "3.8"

services:
  graphql-api:
    build: .
    ports:
      - "4000:3000"
    environment:
      - MONGO_USER=tushartank24
      - MONGO_PASSWORD=d6HVRaiBsjPpLDkE
      - MONGO_DB=events-dev
    restart: unless-stopped
